public/index.html, src/components/EntryForm/FigureInput.tsx, src/components/EntryForm/index.tsx, src/components/EntryForm/styles.css, src/components/EventForm/index.tsx, src/utils/errorTransform.ts, src/utils/form.ts, src/views/Entry/index.tsx, src/views/NewEntry/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/44
- Disable entry form when it is pristine
- Add a prompt when leaving entry form tag if pristine
- Force user to always update to new version in service worker
- Re-use error transform on update and create entry
- Disable submit button on both create and edit entry page
- Show errors on tab if form errored
- Make crisis non-required
=> Add pristine handling on form

src/components/tables/EntriesTable/EntriesFilter/index.tsx, src/components/tables/EntriesTable/index.tsx, src/components/tables/EventsTable/index.tsx, src/views/Admin/UserRoles/UserFilter/index.tsx, src/views/Admin/UserRoles/index.tsx, src/views/Countries/CountriesFilter/index.tsx, src/views/Countries/index.tsx, src/views/Crises/CrisesFilter/index.tsx, src/views/Crises/index.tsx, src/views/Events/EventsFilter/index.tsx, src/views/Extraction/ExtractionEntriesTable/index.tsx, src/views/Extraction/NewExtractionFilters/index.tsx, src/views/Extraction/index.tsx, src/views/Reports/ReportFilter/index.tsx, src/views/Reports/index.tsx
- Fix the issue related to the pagination of tables not being reset to 1, in all the tables that implements pagination feature
=> Fix pagination reset for all tables

package.json, src/components/Navbar/index.tsx, src/components/tableHelpers/index.tsx, src/components/tables/CommunicationAndPartners/CommunicationTable/index.tsx, src/components/tables/EntriesTable/index.tsx, src/views/Actors/ActorTable/index.tsx, src/views/ContextualUpdates/index.tsx, src/views/Crises/index.tsx, src/views/Entry/EntryForm/DetailsInput/index.tsx, src/views/FigureTags/FigureTagsTable/index.tsx, src/views/Organizations/OrganizationTable/OrganizationForm/index.tsx, src/views/Organizations/OrganizationTable/index.tsx, src/views/Reports/index.tsx, yarn.lock
- ShortName field should not be mandatory : https://github.com/idmc-labs/Helix2.0/issues/168#issue-937194080
- Make "actionColumn" as a reusable element in table-helpers
=> Make actionColumn reusable

src/components/Navbar/styles.css, src/views/Entry/EntryForm/AnalysisInput/index.tsx, src/views/Entry/EntryForm/schema.ts, src/views/Extraction/queries.tsx
Addresses :- 
https://github.com/idmc-labs/Helix2.0/issues/166#issue-934998713
https://github.com/idmc-labs/Helix2.0/issues/169#issue-937200072
- Make Analysis Logic fields mandatory in Entry Section as per requirement
- Fix the issue regarding geographic region selection not working in Extraction-Filter
=> Fix Analysis Logic issue and Geo-Regions issue

src/components/tables/EntriesTable/NudeEntryTable/index.tsx, src/views/Extraction/ExtractionEntriesTable/NudeEntryTable/index.tsx
- https://github.com/idmc-labs/Helix2.0/issues/235
- Add Country column in Entries table of a particular event detail
=> Add country column in tables of Event detail

src/components/MarkdownEditor/index.tsx, src/views/Country/ContextualAnalysis/ContextualHistoryList/index.tsx, src/views/Country/ContextualAnalysis/index.tsx, src/views/Country/CountrySummary/SummaryHistoryList/index.tsx, src/views/Country/CountrySummary/index.tsx, src/views/Country/index.tsx, src/views/Crisis/index.tsx, src/views/Entry/EntryForm/DetailsInput/index.tsx, src/views/Entry/EntryForm/FigureInput/index.tsx, src/views/Entry/EntryForm/FigureInput/styles.css, src/views/Entry/EntryForm/GeoLocationInput/index.tsx, src/views/Event/index.tsx, src/views/Report/ReportFigureTable/index.tsx, src/views/Report/index.tsx
- Add "ShowMap" button in Extraction Entry in order to render map only when the showMap button is triggered
=> Add showMap button for maps in Extraction Entry

package.json, src/Root/App/Multiplexer/index.tsx, src/Root/App/index.tsx, src/components/TrafficLightInput/index.tsx, src/components/tables/EntriesTable/index.tsx, src/config/routes.tsx, src/views/Dashboard/EntriesForReview/index.tsx, src/views/Entry/EntryComments/CommentForm/index.tsx, src/views/Entry/EntryComments/ReviewCommentForm/index.tsx, src/views/Entry/EntryComments/ReviewCommentForm/styles.css, src/views/Entry/EntryComments/index.tsx, src/views/Entry/EntryForm/DetailsInput/index.tsx, src/views/Entry/EntryForm/FigureInput/index.tsx, src/views/Entry/EntryForm/index.tsx, src/views/Entry/EntryForm/queries.tsx, src/views/Entry/EntryForm/styles.css, src/views/Entry/index.tsx, src/views/Organizations/OrganizationTable/OrganizationForm/index.tsx, src/views/Organizations/OrganizationTable/index.tsx, src/views/Reports/ReportForm/index.tsx, yarn.lock
- Rename 'category' to 'geogrpahical coverage'
- Set 'day' as default accuracy
- Set 'unknown' as default displacement
- Enable review on entry view page
- Remove two different comment box on review page
- Fix prop values for traffic light inputs
- Hide action buttons on traffic light input if disabled
- Hide page change control on Entries table
- Use network-and-cache for apollo client
Addresses https://github.com/idmc-labs/Helix2.0/pull/263
Addresses https://github.com/idmc-labs/Helix2.0/pull/262
Addresses https://github.com/idmc-labs/Helix2.0/pull/252
Addresses https://github.com/idmc-labs/Helix2.0/pull/251
Addresses https://github.com/idmc-labs/Helix2.0/pull/277
Depends on https://github.com/idmc-labs/helix-server/pull/238
Depends on …
=> Remove entry review page

src/views/Entry/EntryForm/ReviewInput/index.tsx, src/views/Entry/EntryForm/ReviewSaveInput/index.tsx, src/views/Entry/EntryForm/ReviewSaveInput/styles.css, src/views/Entry/EntryForm/index.tsx, src/views/Entry/EntryForm/queries.tsx
- https://freedcamp.com/view/2779007/tasks/panel/task/42836172
- https://github.com/idmc-labs/Helix2.0/issues/259
- https://github.com/idmc-labs/Helix2.0/issues/265
- Allow users to assign reviewers only in editMode
- Integrate a separate query for adding reviewers
=> Add changes to assigning reviewers logic

src/Root/App/Multiplexer/index.tsx, src/views/Admin/UserRoles/UserActions/index.tsx, src/views/Admin/UserRoles/UserFilter/index.tsx, src/views/Admin/UserRoles/index.tsx, src/views/SignIn/index.tsx
- https://github.com/idmc-labs/helix2.0-meta/issues/67#issue-1262987116
- https://github.com/idmc-labs/helix-server/pull/274#issue-1263233362
- Added isAdmin column in users table
- Updated the users query in order to re-fetch after isAdmin is updated
=> Add is-admin column in users table

src/components/tables/EntriesTable/NudeFigureTable/index.tsx, src/components/tables/EventsTable/index.tsx, src/views/Extraction/ExtractionEntriesTable/NudeFigureTable/index.tsx, src/views/Report/ReportEventTable/index.tsx, src/views/Report/ReportFigureTable/index.tsx
- issue: https://github.com/idmc-labs/helix2.0-meta/issues/71#issue-1263012357
- Re-arrange the ordering of crisis columns throughout helix project
=> Fix the order of crisis column in multiple tables

src/components/ButtonLikeLink/index.tsx, src/components/tableHelpers/Action.tsx, src/components/tables/EntriesTable/NudeFigureTable/index.tsx, src/views/Dashboard/EntriesForReview/index.tsx, src/views/Extraction/ExtractionEntriesTable/NudeFigureTable/index.tsx, src/views/Report/ReportFigureTable/index.tsx
- Enable new route logic to edit buttons for entries table to redirect to respective figure ID
- **Also add missing route logic to figure category columns to respective figure tables throughout the helix project**
=> Add route logic to edit button in figure tables

src/views/Entry/EntryForm/FigureInput/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/104#issue-1285633013
- Edit disabled mode for sources field on figure-input
=> Fix sources field not disabled in figure-input

src/components/forms/ContactForm/index.tsx, src/components/lists/MyResources/GroupForm/index.tsx, src/components/lists/MyResources/ResourceForm/index.tsx, src/components/lists/MyResources/index.tsx, src/hooks/toggleBasicState.ts
- Add fixes to my resource logic not refreshing instantly after new creation or update
- Feature to add new group name to the group-field of resource form
- Replace re-fetch logic of my resources
- Add functionality to add newly added group to the resource form instantly
=> Fix re-fetch query logic of resources component

src/views/Organizations/OrganizationTable/OrganizationForm/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/152
- server: https://github.com/idmc-labs/helix-server/pull/320#issue-1326855344
- Make countries field not required in the organization form
=> Make countries field non required

src/views/Entry/EntryForm/AgeInput/index.tsx, src/views/Entry/EntryForm/FigureInput/index.tsx, src/views/Entry/EntryForm/schema.ts
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/160
- Update gender field in age input and make "unspecified" as default selected
- Also make gender field required
=> Update gender field in age input

src/components/tables/EventsTable/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/177#issue-1325995699
- Fix the issue of events table in crisis page by adding extra crisisByIds argument in events query variable
=> Fix the issue by adding separate crisis id

src/components/tables/EntriesFiguresTable/NudeFigureTable/index.tsx, src/views/Entry/EntryForm/FigureInput/index.tsx, src/views/Extraction/ExtractionEntriesTable/NudeFigureTable/index.tsx, src/views/Report/ReportFigureTable/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/154
- https://github.com/idmc-labs/helix-server/pull/308/files
- Addition of stock_date and stock_reporting_date in figureList query
- Addition of columns in figure table
=> Add stock date columns in figures table

src/components/GeoInput/index.tsx, src/views/Entry/EntryForm/AgeInput/index.tsx, src/views/Entry/EntryForm/DetailsInput/index.tsx, src/views/Entry/EntryForm/FigureInput/index.tsx, src/views/Entry/EntryForm/GeoLocationInput/index.tsx, src/views/Entry/EntryForm/GeoLocationInput/styles.css, src/views/Entry/EntryForm/index.tsx
Related to https://github.com/idmc-labs/helix2.0-meta/issues/110
Related to https://github.com/idmc-labs/helix2.0-meta/issues/170
Related to https://github.com/idmc-labs/helix2.0-meta/issues/183
Related to https://github.com/idmc-labs/helix2.0-meta/issues/148 
- Add a mapping to infer accuracy on Location
- Show name instead of district and town on Location
- Show 'DH' if term is destroyed housing on figure title
=> Enable editing document and url fields on Entry

src/components/selections/OrganizationMultiSelectInput/index.tsx, src/components/selections/OrganizationSelectInput/index.tsx, src/components/tables/EntriesFiguresTable/NudeFigureTable/index.tsx, src/views/Entry/EntryForm/FigureInput/index.tsx, src/views/Extraction/ExtractionEntriesTable/NudeFigureTable/index.tsx, src/views/Report/ReportFigureTable/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/188#issue-1344211753
- Server branch: https://github.com/idmc-labs/helix-server/pull/336#issue-1377666049
- Add location, housing, idu and sources reliability columns for all the figure tables
- Also add logic to show only respective organizations of the chosen country
=> Add multiple columns for figure tables

src/Root/App/Multiplexer/index.tsx, src/components/tables/EventsEntriesFiguresTable/EventsFilter/index.tsx, src/components/tables/EventsTable/index.tsx, src/types/index.ts, src/views/SignIn/index.tsx
- issue: https://github.com/idmc-labs/helix2.0-meta/issues/172
- server branch: https://github.com/idmc-labs/helix-server/pull/323#issue-1338610590
- Add a feature to pre-select options in the QA filter based upon the condition that if the user is Regional-Coordinator or Monitoring-Expert
=> Enable auto-selected fields for QA filters

src/Root/App/index.tsx, src/components/tableHelpers/SymbolCell/index.tsx, src/components/tableHelpers/SymbolCell/styles.css, src/components/tables/EntriesFiguresTable/NudeFigureTable/index.tsx, src/views/Entry/EntryForm/FigureInput/index.tsx, src/views/Extraction/ExtractionEntriesTable/NudeFigureTable/index.tsx, src/views/Report/ReportFigureTable/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/339
- Triangle symbol for "Sources and reliability" column for all figures
- Add a column in all figure tables that showcases a 'triangle' symbol
- Color of the triangle is based upon the sources and reliability data
=> Add triangle symbol based upon sources

src/components/forms/ContactForm/index.tsx, src/components/selections/OrganizationMultiSelectInput/index.tsx, src/components/selections/OrganizationSelectInput/index.tsx, src/components/tables/EventsEntriesFiguresTable/EventsFilter/index.tsx, src/views/Entry/EntryForm/queries.tsx, src/views/Extraction/ExtractionFilters/index.tsx
- Use idmcShortName instead of name for countries
- Do not set default values for events if not in qa mode
Depends on https://github.com/idmc-labs/helix-server/pull/341
=> Order organizations by selected country

package.json, src/components/TrafficLightInput/ReviewComments/CommentForm/index.tsx, src/components/forms/EntryForm/FigureInput/index.tsx, src/components/forms/EntryForm/index.tsx, src/components/forms/EntryForm/queries.tsx, src/views/Entry/index.tsx, src/views/EventReview/index.tsx, yarn.lock
Depends on https://github.com/idmc-labs/helix-server/pull/392
- Show traffic lights by default
- Use confirmation button for Clear and Remove button on Figure
- Hide "Edit Figure" link on "Entry Edit" page
- Make "comment" non-mandatory for "GREEN" review type
=> Display reviews on "Entry Edit" page

src/components/QuickActionButton/styles.css, src/components/QuickActionConfirmButton/styles.css, src/components/QuickActionLink/styles.css, src/components/tableHelpers/index.tsx, src/components/tableHelpers/styles.css, src/components/tables/ContactsTable/CommunicationTable/index.tsx, src/components/tables/ContactsTable/index.tsx, src/components/tables/EntriesFiguresTable/NudeEntryTable/index.tsx, src/components/tables/EntriesFiguresTable/NudeFigureTable/index.tsx, src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/EventsAction/index.tsx, src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/index.tsx, src/components/tables/ParkedItemTable/index.tsx, src/views/Actors/ActorTable/index.tsx, src/views/Admin/UserRoles/index.tsx, src/views/ContextualUpdates/index.tsx, src/views/Crises/index.tsx, src/views/Extraction/ExtractionEntriesTable/NudeEntryTable/index.tsx, src/views/Extraction/ExtractionEntriesTable/NudeFigureTable/index.tsx, src/views/FigureTags/FigureTagsTable/index.tsx, src/views/Notifications/index.tsx, src/views/Organizations/OrganizationTable/index.tsx, src/views/Reports/index.tsx, src/views/ViolenceContext/ViolenceContextTable/index.tsx
- Adjust a specified width for all sticky columns
- Server branch: https://github.com/idmc-labs/helix-server/pull/374#issue-1453018264 
- Add a logic to calculate generic sizes for all icons of sticky action columns
=> Add fixes for all sticky action columns 

src/components/lists/MyResources/ResourcesAccordion/index.tsx, src/components/lists/MyResources/ResourcesAccordion/styles.css, src/views/QADashboard/index.tsx, src/views/QADashboard/styles.css
- Issue:  https://github.com/idmc-labs/helix2.0-meta/issues/245#issue-1492194052
- Add a header for the list of tab options in the side bar section of QA page
=> Add a category heading for QA tab options

src/components/selections/EventListSelectInput/index.tsx, src/components/tables/EventsEntriesFiguresTable/EventsFilter/index.tsx, src/views/Event/index.tsx, src/views/Reports/ReportForm/index.tsx
- https://github.com/idmc-labs/helix2.0-meta/issues/320#issue-1574990399
- https://github.com/idmc-labs/helix-server/pull/438
- Replace "Disaster Types" by "Hazard Types"
=> Replace disaster types by hazard types

src/Root/App/Multiplexer/index.tsx, src/types/index.ts, src/utils/common.ts, src/views/Report/index.tsx
- Feature to show public figure analysis data in GIDD
- Server branch: https://github.com/idmc-labs/helix-server/pull/454#issue-1677898394
- Add toggle button in "Public Figure Analysis" section in the report detail
=> Add feature to show public figure in gidd

src/components/forms/UserEmailChangeForm/index.tsx, src/components/forms/UserEmailChangeForm/styles.css, src/views/Admin/UserRoles/UserActions/index.tsx, src/views/Admin/UserRoles/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/191#issuecomment-1576468157
- Server branch:  https://github.com/idmc-labs/helix-server/pull/493#issue-1735771174
- Add an edit button for each row in the ADMIN section
- Enable edit mode for each user using a modal that contains firstName, lastName and Email as the input fields
=> Add a modal to update the email of users in admin section

.github/workflows/ci.yml, docker-compose.yml, src/views/Admin/UserRoles/UserActions/index.tsx, src/views/Admin/UserRoles/index.tsx, src/views/ApiUsage/index.tsx, src/views/ApiUsage/styles.css, src/views/Crisis/index.tsx, src/views/Event/index.tsx
- Add links to graphiql and swagger endpoints
- Show which date was used to calcualte stock data on crisis and event
- https://github.com/idmc-labs/helix-server/pull/505
- https://github.com/idmc-labs/helix2.0-meta/issues/863
- https://github.com/idmc-labs/helix2.0-meta/issues/264
- https://github.com/idmc-labs/helix2.0-meta/issues/696
=> Add feature to add user as director's office and reporting team

src/components/forms/EntryForm/schema.ts, src/components/tableHelpers/ExternalLink/index.tsx, src/views/ApiUsage/ApiRecordsTable/index.tsx
- Limit adding future dates on start date, end date and stock date on figures
- https://github.com/idmc-labs/helix-server/pull/521
=> Add columns on API usage table

package.json, src/Root/App/index.tsx, src/components/forms/EntryForm/FigureInput/index.tsx, src/components/forms/EntryForm/index.tsx, yarn.lock
- Override network error if we have graphql errors
- Fix event options issue after failure on entry form
- Move non field errors to the top
=> Update apollo to override networkError
