- package.json
- src/Root/App/Multiplexer/index.tsx
- src/utils/form.ts
- src/utils/schema.d.ts
- src/utils/schema.js
- src/views/NewEntry/index.tsx
- src/views/NewEntry/styles.css
- Fix errors access on validation
- Use optional chaining for validation
- Fix loading on Multiplexer
- Add sample form
> Add useFormObject and userFormArray hooks

- package.json
- src/Root/App/index.tsx
- Fix serve command
- Update toggle-ui version to latest
> Fix style import order

- src/Root/App/Multiplexer/index.tsx
- src/components/CrisisForm/index.tsx
- src/components/EventForm/index.tsx
- src/utils/errorTransform.ts
- src/utils/form.ts
- src/views/NewEntry/AgeInput.tsx
- src/views/NewEntry/AnalysisInput.tsx
- src/views/NewEntry/DetailsInput.tsx
- src/views/NewEntry/FigureInput.tsx
- src/views/NewEntry/ReviewInput.tsx
- src/views/NewEntry/StrataInput.tsx
- src/views/NewEntry/index.tsx
- src/views/SignIn/index.tsx
- src/views/SignUp/index.tsx
- Disable elements when data is loading
- Disable elements when action is loading
- Convert server errors to form errors
> Display errors from server

- config/webpack.dev.js
- package.json
- src/Root/App/index.tsx
- src/components/Container/index.tsx
- src/components/Container/styles.css
- src/components/Footer/index.tsx
- src/components/Footer/styles.css
- src/components/Navbar/index.tsx
- src/components/Navbar/styles.css
- src/types/index.ts
- src/views/Crises/index.tsx
- src/views/Crises/styles.css
- yarn.lock
- Change watchQuery options
- Add subnavbar
- Show user information on navbar
A lot of the features on table are still missing. It's a work in progress and the usage can change.
> Add table for crisis with sorting

- .eslintrc.js
- config/webpack.dev.js
- config/webpack.prod.js
- package.json
- postcss.config.js
- src/Root/App/Multiplexer/index.tsx
- src/Root/App/Multiplexer/route/index.tsx
- src/Root/App/Multiplexer/route/styles.css
- src/Root/App/Multiplexer/styles.css
- src/components/Navbar/index.tsx
- src/components/QuickActionButton/styles.css
- src/types/index.ts
- src/utils/typings.ts
- src/views/Crises/index.tsx
- src/views/Crises/styles.css
- src/views/FourHundredThree/index.tsx
- src/views/FourHundredThree/styles.css
- src/views/SignIn/index.tsx
- yarn.lock
- Make Performance and Admin page accessible to only super user
- Create postCSS config file
- Update eslint plugin for react hooks
- Update toggle-ui
- Add delete and edit buttons (on crisis table)
> Add 403 page

- src/components/CrisisForm/index.tsx
- src/components/EventForm/index.tsx
- src/hooks/toggleBasicState.ts
- src/views/Dashboard/MyResources/GroupForm/index.tsx
- src/views/Dashboard/MyResources/ResourceForm/index.tsx
- src/views/Dashboard/MyResources/ResourcesAccordion/index.tsx
- src/views/Dashboard/MyResources/SearchResourceForm/index.tsx
- src/views/Dashboard/MyResources/index.tsx
- src/views/Dashboard/MyResources/myResources.interface.ts
- src/views/Dashboard/index.tsx
- src/views/SignIn/index.tsx
- src/views/SignUp/index.tsx
- Pass error on form fields
- Add comments
- Fix typings on submit
> Use PartialForm interface for errors

- src/Root/App/styles.css
- src/components/CrisisForm/index.tsx
- src/components/EventForm/index.tsx
- src/components/Navbar/index.tsx
- src/components/Navbar/styles.css
- src/views/Crisis/index.tsx
- src/views/NewEntry/DetailsInput.tsx
- src/views/NewEntry/index.tsx
- Load event data for event form
- Edit event form
> Add disabled color on links on navbar (for incomplete pages)

- src/components/tableHelpers/Action.tsx
- src/components/tableHelpers/Date.tsx
- src/components/tableHelpers/ExternalLink.tsx
- src/views/Crisis/index.tsx
- src/views/Dashboard/MyResources/ResourceForm/index.tsx
- src/views/Dashboard/MyResources/index.tsx
- src/views/Extraction/index.tsx
- src/views/Extraction/styles.css
- src/views/NewEntry/DetailsInput.tsx
- src/views/NewEntry/index.tsx
> Get entries

- src/components/Loading/index.tsx
- src/components/Loading/styles.css
- src/components/Navbar/index.tsx
- src/components/tableHelpers/Date.tsx
- src/views/Crises/index.tsx
- src/views/Crisis/index.tsx
- src/views/Extraction/index.tsx
> Use Loading message

- src/Root/App/Multiplexer/index.tsx
- src/Root/App/Multiplexer/route/index.tsx
- src/components/ButtonLikeLink/index.tsx
- src/components/ButtonLikeLink/styles.css
- src/components/EntriesTable/index.tsx
- src/components/EntriesTable/styles.css
- src/components/EntryForm/index.tsx
- src/components/EntryForm/types.ts
- src/components/Navbar/index.tsx
- src/components/Navbar/styles.css
- src/components/QuickActionLink/index.tsx
- src/components/QuickActionLink/styles.css
- src/components/tableHelpers/Action.tsx
- src/views/Entry/index.tsx
- src/views/Entry/styles.css
Depends on: https://github.com/idmc-labs/helix-server/pull/36
> Add support for entry edit

- src/Root/App/Multiplexer/index.tsx
- src/Root/App/Multiplexer/route/index.tsx
- src/components/CommunicationAndPartners/CommunicationTable/CommunicationForm/index.tsx
- src/components/CommunicationAndPartners/CommunicationTable/index.tsx
- src/components/CommunicationAndPartners/ContactForm/index.tsx
- src/components/CommunicationAndPartners/index.tsx
- src/components/EntriesTable/index.tsx
- src/components/MyResources/ResourceForm/index.tsx
- src/components/MyResources/index.tsx
- src/components/Navbar/index.tsx
- src/views/Countries/ContextualUpdates/index.tsx
- src/views/Countries/ContextualUpdates/styles.css
- src/views/Countries/CountrySummary/index.tsx
- src/views/Countries/CountrySummary/styles.css
- src/views/Countries/index.tsx
- src/views/Countries/styles.css
- src/views/Crises/index.tsx
- src/views/Crisis/index.tsx
- src/views/Event/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/45
> Filter countrywise data

- README.md
- package.json
- public/index.html
- src/Root/App/Multiplexer/index.tsx
- src/Root/index.tsx
- src/Root/styles.css
- src/components/BrandHeader/index.tsx
- src/views/Error/index.tsx
- src/views/Error/styles.css
- src/views/FourHundredFour/index.tsx
- src/views/FourHundredThree/index.tsx
- yarn.lock
- Add sentry error boundary
- Update all env variables placeholder on Readme
- Create Error component (use it as fallback)
> Enable sentry on production

- codegen.yml
- package.json
- schema.graphql
- src/Root/App/index.tsx
- src/components/CountryMultiSelectInput/index.tsx
- src/components/CountrySelectInput/index.tsx
- src/components/EntryForm/FigureInput/index.tsx
- src/components/EntryForm/FigureInput/styles.css
- src/components/GeoInput/index.tsx
- src/components/GeoInput/styles.css
- src/views/Countries/index.tsx
- src/views/Countries/styles.css
- yarn.lock
Depends on https://github.com/toggle-corp/re-map/pull/9
> Add query to search on osmnames

- package.json
- src/Root/App/index.tsx
- yarn.lock
Depends on https://github.com/idmc-labs/helix-server/pull/35
> Enable batched request

- src/components/CommunicationAndPartners/CommunicationTable/CommunicationForm/index.tsx
- src/components/CommunicationAndPartners/CommunicationTable/index.tsx
- src/components/CommunicationAndPartners/ContactForm/index.tsx
- src/components/CommunicationAndPartners/index.tsx
- src/components/ContextualUpdate/ContextualUpdateForm.tsx
- src/components/CountrySummary/CountrySummaryForm.tsx
- src/components/CrisisForm/index.tsx
- src/components/EntriesTable/index.tsx
- src/components/EntryForm/ReviewInput/index.tsx
- src/components/EntryForm/queries.tsx
- src/components/EventForm/index.tsx
- src/components/MyResources/GroupForm/index.tsx
- src/components/MyResources/ResourceForm/index.tsx
- src/components/MyResources/ResourceItem/index.tsx
- src/components/OrganizationTable/OrganizationForm/index.tsx
- src/components/OrganizationTable/index.tsx
- src/components/PageHeader/index.tsx
- src/components/UserRoles/UserRoleForm.tsx
- src/components/UserRoles/index.tsx
- src/config/routes.tsx
- src/views/Crises/index.tsx
- src/views/Crisis/index.tsx
- src/views/SignIn/index.tsx
- src/views/SignUp/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/62
> Change gql schema for errors

- src/Root/App/Multiplexer/index.tsx
- src/components/ActorTable/ActorForm/index.tsx
- src/components/ActorTable/ActorForm/styles.css
- src/components/ActorTable/index.tsx
- src/components/ActorTable/styles.css
- src/components/Navbar/index.tsx
- src/config/routes.tsx
- src/views/Actors/index.tsx
- src/views/Actors/styles.css
Depends on https://github.com/idmc-labs/helix-server/pull/63
> CRUD of actor

- src/components/EventForm/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/69
> Add event others subtypes

- package.json
- src/components/EntryForm/FigureInput/index.tsx
- src/components/EventsTable/index.tsx
- src/components/GeoInput/index.tsx
- src/components/GeoInput/styles.css
- src/components/Heading/index.tsx
- src/components/Heading/styles.css
- src/components/Loading/index.tsx
- src/declarations/turf.d.ts
- yarn.lock
- Add fit-to-country and fit-to-locations
- Show temporary location on hover
- Persist last bounds
- Disable GeoInput in review mode
> Add improvements on geo-location input

- .github/workflows/ci.yml
- README.md
- aws/cloudformation.yml
- Add Deployment cloudformation template.
- Add CI/CD for alpha/prod/nightly branch.
> Add CI for Deployment/Test

- src/components/EntryForm/GeoLocationInput/index.tsx
- src/components/EntryForm/types.ts
- src/components/EntryForm/utils.ts
- src/components/Loading/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/79
- Use key `geoLocation` instead of `geoLocationId`
> Use id instead of uuid for geolocation

- src/components/EntryForm/FigureInput/index.tsx
- src/components/EntryForm/GeoLocationInput/index.tsx
- src/components/EntryForm/schema.ts
- src/components/GeoInput/index.tsx
- Make districts and town non-mandatory
- Only show map after country is selected
- Add total figure calculation for household size
- Change "identifier" to "origin"
Depends https://github.com/idmc-labs/helix-server/pull/82
> Move districts and town after map

- src/components/EntryForm/GeoLocationInput/index.tsx
- src/components/FigureTagsTable/styles.css
- src/components/GeoInput/index.tsx
- src/components/ParkingLotTable/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/88
> Change "SOURCE" to "ORIGIN"

- src/components/CommunicationAndPartners/CommunicationTable/CommunicationForm/index.tsx
- src/components/CommunicationAndPartners/CommunicationTable/index.tsx
- src/components/CommunicationAndPartners/ContactForm/index.tsx
- src/components/CommunicationAndPartners/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/90
> Fix contacts for changes in server

- src/components/EntryForm/FigureInput/index.tsx
- src/components/EntryForm/GeoLocationInput/index.tsx
- src/components/EntryForm/index.tsx
- src/components/EntryForm/queries.tsx
- src/components/EntryForm/schema.ts
- src/components/GeoInput/index.tsx
> Add isHousingDestroyed value

- src/components/ContextualUpdate/ContextualHistoryList/index.tsx
- src/components/ContextualUpdate/ContextualUpdateForm/index.tsx
- src/components/ContextualUpdate/index.tsx
- src/components/ContextualUpdate/styles.css
- src/components/Row/index.tsx
- src/components/Row/styles.css
- src/views/Countries/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/99
> Show publishDate and crisisType on contextual update table and forms

- src/Root/App/Multiplexer/index.tsx
- src/components/EntryForm/ReviewInput/index.tsx
- src/components/EntryForm/index.tsx
- src/components/EntryForm/queries.tsx
- src/components/EntryForm/schema.ts
- src/components/EntryForm/types.ts
- src/components/EntryForm/utils.ts
- src/components/ParkedItemForm/index.tsx
- src/components/ParkedItemTable/Action/index.tsx
- src/components/ParkedItemTable/Action/styles.css
- src/components/ParkedItemTable/index.tsx
- src/config/routes.tsx
- src/views/Entry/index.tsx
Depends on: https://github.com/idmc-labs/helix-server/pull/101
> Load entry form from parked item and create entry

- src/components/ContextualUpdate/ContextualUpdateForm/styles.css
- src/components/EntriesTable/index.tsx
- src/components/EntryForm/index.tsx
- src/components/EntryForm/queries.tsx
- src/components/EventsTable/index.tsx
- src/views/Crises/index.tsx
- src/views/Extraction/ExtractionEntriesTable/index.tsx
- src/views/Extraction/NewExtractionFilters/index.tsx
- src/views/Extraction/queries.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/93
> Add stock/flow figures in table

- src/components/EntryForm/DetailsInput/index.tsx
- src/components/EntryForm/index.tsx
- src/components/EntryForm/queries.tsx
- src/components/EntryForm/types.ts
- src/components/UrlPreview/index.tsx
- src/views/Entry/index.tsx
- src/views/Entry/styles.css
- Add a new tab "Cached Preview"
Depends on https://github.com/idmc-labs/helix-server/pull/102
> Generate source preview and poll for preview

- src/components/CommunicationAndPartners/CommunicationTable/CommunicationForm/index.tsx
- src/components/CommunicationAndPartners/CommunicationTable/index.tsx
- src/views/Extraction/NewExtractionFilters/index.tsx
- src/views/Extraction/queries.tsx
- Remove title from communication
Depends on https://github.com/idmc-labs/helix-server/pull/117
> Make event crisis multiselection on extraction

- README.md
- src/Root/App/Multiplexer/index.tsx
- src/components/EntryComments/queries.tsx
- src/components/Navbar/index.tsx
- src/components/UserRoles/UserRoleForm/index.tsx
- src/components/UserRoles/index.tsx
- src/types/index.ts
- src/views/SignIn/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/118
> Remove all references to username

- src/Root/App/Multiplexer/index.tsx
- src/components/DomainContext.ts
- src/components/EntriesTable/styles.css
- src/components/Navbar/index.tsx
- src/components/UserProfileUpdateForm/index.tsx
- src/components/UserProfileUpdateForm/styles.css
- src/views/Extraction/ExtractionEntriesTable/styles.css
- start.bat
* Implemented the Update profile update.
> Feature/user profile : update profile

- src/views/Reports/ReportForm/index.tsx
Feature/region
Depends on https://github.com/idmc-labs/helix-server/pull/133
> Added region multiselect for the reports

- src/views/Entry/index.tsx
- src/views/Entry/styles.css
Related to https://github.com/idmc-labs/Helix2.0/issues/68
> Changes on color of "Cached preview" tab-name on failed condition

- src/components/selections/GeographicMultiSelectInput/index.tsx
- src/components/selections/GeographicMultiSelectInput/styles.css
- src/views/Extraction/NewExtractionFilters/index.tsx
- src/views/Extraction/queries.tsx
- src/views/Reports/ReportForm/index.tsx
Related to https://github.com/idmc-labs/Helix2.0/issues/62
> Added GeographicalGroup selection in Reports/Extraction

- src/utils/validation.ts
- src/views/Entry/EntryForm/schema.ts
Related to https://github.com/idmc-labs/Helix2.0/issues/75
> Implemented validation on the numeric elements of entry form

- src/components/GeoInput/index.tsx
- src/components/forms/CrisisForm/index.tsx
- src/components/forms/EventForm/index.tsx
- src/components/forms/UserProfileUpdateForm/index.tsx
- src/components/lists/MyResources/ResourceForm/index.tsx
- src/components/tables/CommunicationAndPartners/CommunicationTable/CommunicationForm/index.tsx
- src/components/tables/CommunicationAndPartners/ContactForm/index.tsx
- src/components/tables/ParkedItemTable/ParkedItemForm/index.tsx
- src/views/Actors/ActorTable/ActorForm/index.tsx
- src/views/Entry/EntryComments/CommentForm/index.tsx
- src/views/Entry/EntryForm/index.tsx
- src/views/Extraction/NewExtractionFilters/index.tsx
- src/views/FigureTags/FigureTagsTable/FigureTagForm/index.tsx
- src/views/Organizations/OrganizationTable/OrganizationForm/index.tsx
- src/views/Report/Analysis/AnalysisUpdateForm/index.tsx
- src/views/Report/Challenges/ChallengesUpdateForm/index.tsx
- src/views/Report/Methodology/MethodologyUpdateForm/index.tsx
- src/views/Report/ReportComments/CommentForm/index.tsx
- src/views/Report/Significant/SignificantUpdatesForm/index.tsx
- src/views/Report/Summary/SummaryUpdateForm/index.tsx
- src/views/Reports/ReportForm/index.tsx
Related to https://github.com/idmc-labs/Helix2.0/issues/102
> Memoized variables that are used in query

- src/components/forms/CrisisForm/index.tsx
- src/components/forms/EventForm/index.tsx
- src/components/forms/UserProfileUpdateForm/index.tsx
- src/views/Admin/UserRoles/UserRoleForm/index.tsx
- src/views/Countries/CountriesFilter/index.tsx
- src/views/Country/ContextualAnalysis/ContextualAnalysisForm/index.tsx
- src/views/Crises/CrisesFilter/index.tsx
- src/views/Entry/EntryForm/AgeInput/index.tsx
- src/views/Entry/EntryForm/index.tsx
- src/views/Events/EventsFilter/index.tsx
- src/views/Extraction/NewExtractionFilters/index.tsx
- src/views/Reports/ReportForm/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/150
> Rename Event Types and Crisis Types to cause

- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/index.tsx
- src/views/Entry/EntryForm/queries.tsx
- src/views/Entry/EntryForm/schema.ts
- src/views/Entry/EntryForm/types.ts
Related to https://github.com/idmc-labs/Helix2.0/issues/51
> Added SelectOption based upon displacementOccured in entryForm

- src/views/Entry/index.tsx
- src/views/Report/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/156
> Manually start/stop polling request

- src/Root/App/Multiplexer/index.tsx
- src/components/GeoInput/index.tsx
- src/components/forms/CrisisForm/index.tsx
- src/components/forms/EventForm/index.tsx
- src/components/lists/MyResources/ResourceForm/index.tsx
- src/components/selections/CountryMultiSelectInput/index.tsx
- src/components/selections/CountrySelectInput/index.tsx
- src/components/tables/CommunicationAndPartners/CommunicationTable/CommunicationForm/index.tsx
- src/components/tables/CommunicationAndPartners/ContactForm/index.tsx
- src/components/tables/CommunicationAndPartners/index.tsx
- src/components/tables/EventsTable/index.tsx
- src/components/tables/ParkedItemTable/ParkedItemForm/index.tsx
- src/components/tables/ParkedItemTable/index.tsx
- src/views/Actors/ActorTable/ActorForm/index.tsx
- src/views/Actors/ActorTable/index.tsx
- src/views/ContextualUpdates/index.tsx
- src/views/Countries/index.tsx
- src/views/Country/index.tsx
- src/views/Crises/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/queries.tsx
- src/views/Extraction/index.tsx
- src/views/Extraction/queries.tsx
- src/views/Report/ReportCountryTable/index.tsx
- src/views/Report/index.tsx
- src/views/Reports/ReportForm/index.tsx
- src/views/Reports/index.tsx
Related to https://github.com/idmc-labs/Helix2.0/issues/43
Depends on https://github.com/idmc-labs/helix-server/pull/144
> Added Download buttons on countries, crises and events section

- src/components/tables/EventsTable/index.tsx
- src/views/Countries/index.tsx
- src/views/Crises/index.tsx
- src/views/Extraction/index.tsx
- src/views/Report/ReportFigureTable/index.tsx
- src/views/Report/ReportFigureTable/styles.css
- src/views/Report/index.tsx
- src/views/Report/styles.css
Related to https://github.com/idmc-labs/Helix2.0/issues/96
> Add Figures Table on details of each report

- src/components/tables/EntriesTable/EntriesFilter/index.tsx
- src/components/tables/EntriesTable/EntriesFilter/styles.css
- src/components/tables/EntriesTable/index.tsx
- src/views/Dashboard/index.tsx
- src/views/Entry/EntryForm/ReviewInput/index.tsx
- src/views/Entry/EntryForm/queries.tsx
- src/views/Extraction/NewExtractionFilters/index.tsx
- src/views/Extraction/queries.tsx
- src/views/Reports/ReportFilter/index.tsx
- src/views/Reports/index.tsx
- Added status filter in the filtering component of Reports
- Addition of status filter in Extraction section is in progress
--> Also Depends on : https://github.com/idmc-labs/helix-server/pull/161
Related to https://github.com/idmc-labs/Helix2.0/issues/82
> Add Status Filter in Report filter section

- src/components/Downloads/index.tsx
- src/components/tables/EntriesTable/index.tsx
- src/components/tables/EventsTable/index.tsx
- src/views/Countries/index.tsx
- src/views/Country/index.tsx
- src/views/Crises/index.tsx
- src/views/Extraction/ExtractionEntriesTable/index.tsx
- src/views/Report/ReportCountryTable/index.tsx
- src/views/Report/ReportCrisisTable/index.tsx
- src/views/Report/ReportEntryTable/index.tsx
- src/views/Report/ReportEventTable/index.tsx
- src/views/Reports/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/165
> Update UI wrt api for aggregated values

- src/components/ProgressBar/index.tsx
- src/components/ProgressBar/styles.css
- src/components/tableHelpers/StackedProgress/index.tsx
- src/components/tableHelpers/StackedProgress/styles.css
- src/components/tables/EventsTable/index.tsx
- src/views/Crises/index.tsx
- src/views/Report/ReportCrisisTable/index.tsx
- src/views/Report/ReportEntryTable/index.tsx
- src/views/Report/ReportEventTable/index.tsx
- src/views/Report/ReportFigureTable/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/175
> Add ProgressBar component

- README.md
- package.json
- src/components/BrandHeader/index.tsx
- src/components/BrandHeader/styles.css
- src/components/HCaptcha/index.tsx
- src/views/SignIn/index.tsx
- src/views/SignIn/styles.css
- src/views/SignUp/index.tsx
- src/views/SignUp/styles.css
- yarn.lock
- Add React hCaptcha Component Library and implementing it on the SignIn section and SignUp section
#Remaining:
- Works of exchanging data to server 
Depends on https://github.com/idmc-labs/helix-server/pull/168
> Add hCaptcha on SignIn component

- src/views/Dashboard/EntriesForReview/index.tsx
- src/views/SignUp/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/181
> Don't send confirmation password to server

- src/components/selections/ReviewersMultiSelectInput/index.tsx
- src/components/selections/UserSelectInput/index.tsx
- src/views/Report/index.tsx
- Sort generations by descending order
> Explicitly define active users

- src/components/View/index.tsx
- src/views/Entry/EntryForm/index.tsx
- src/views/Extraction/index.tsx
- src/views/SignUp/index.tsx
- replaced the redirection logic with history.push()
> Replace Redirect logic with useHistory logic

- src/views/Country/index.tsx
- Add crises and events count separartely for each Country detail caused by Conflict & Disasters
> Add crises & events count based upon Conflict/Disasters

- src/views/Entry/EntryForm/queries.tsx
Addresses https://freedcamp.com/view/2779007/issuetracker/panel/issue/207261
* While editing a entry, fetch breakdown and reliability information on publishers and sources
> Show publisher/organization info on edit

- src/components/Downloads/DownloadedItem/index.tsx
- src/components/Downloads/styles.css
- src/components/Section/index.tsx
- src/views/Entry/EntryForm/AgeInput/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/index.tsx
- src/views/Entry/index.tsx
- src/views/Report/index.tsx
Related to https://github.com/idmc-labs/Helix2.0/issues/140
Related to https://github.com/idmc-labs/Helix2.0/issues/139
Depends on https://github.com/idmc-labs/helix-server/pull/186
- Fix height issue with download popup
- Add "KILLED" state in export
> Add "KILLED" state in export

- src/components/InfoIcon/styles.css
- src/components/selections/EventMultiSelectInput/index.tsx
- src/components/selections/EventMultiSelectInput/styles.css
- src/hooks/useModalState.ts
- src/views/Entry/EntryForm/EntryCloneForm/index.tsx
- src/views/Entry/EntryForm/EntryCloneForm/styles.css
- src/views/Entry/EntryForm/index.tsx
- src/views/Entry/EntryForm/styles.css
- src/views/Entry/index.tsx
- src/views/Entry/styles.css
- src/views/Event/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/188
Related to https://github.com/idmc-labs/Helix2.0/issues/129
Related to https://github.com/idmc-labs/Helix2.0/issues/156
- Enable entry clone modal (if there are no changes and entry exists on
server)
- Add Multiselect input to select events
> Add entry clone modal

- .github/workflows/ci.yml
* Nightly api points to new `helix` server
> Update nightly api url

- README.md
- config/webpack.dev.js
- config/webpack.prod.js
- package.json
- public/index.html
- src/components/BrandHeader/index.tsx
Related to https://github.com/idmc-labs/Helix2.0/issues/162
> Change name "Helix" to "Helix 2.0"

- .github/workflows/ci.yml
> Update alpha api url

- .eslintrc-loader.js
- .eslintrc.js
- src/components/GeoInput/index.tsx
- src/components/TrafficLightInput/index.tsx
- src/components/forms/EventForm/index.tsx
- src/components/tables/ParkedItemTable/ParkedItemForm/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/index.tsx
- src/views/Entry/EntryForm/schema.ts
> Make enums typesafe

- src/views/Admin/UserRoles/index.tsx
> Fix value for register variable

- src/components/selections/UserMultiSelectInput/index.tsx
- src/components/selections/UserMultiSelectInput/styles.css
- src/components/tables/CommunicationAndPartners/ContactsFilter/index.tsx
- src/components/tables/CommunicationAndPartners/ContactsFilter/styles.css
- src/components/tables/CommunicationAndPartners/index.tsx
- src/components/tables/ParkedItemTable/ParkedItemFilter/index.tsx
- src/components/tables/ParkedItemTable/ParkedItemFilter/styles.css
- src/components/tables/ParkedItemTable/index.tsx
- src/views/Actors/ActorTable/ActorFilters/index.tsx
- src/views/Actors/ActorTable/ActorFilters/styles.css
- src/views/Actors/ActorTable/index.tsx
- src/views/ContextualUpdates/ContextualUpdateFilter/index.tsx
- src/views/ContextualUpdates/ContextualUpdateFilter/styles.css
- src/views/ContextualUpdates/index.tsx
- src/views/FigureTags/FigureTagsTable/index.tsx
- src/views/FigureTags/TagsFilter/index.tsx
- src/views/FigureTags/TagsFilter/styles.css
- src/views/Organizations/OrganizationTable/OrganizationFilter/index.tsx
- src/views/Organizations/OrganizationTable/OrganizationFilter/styles.css
- src/views/Organizations/OrganizationTable/index.tsx
- Includes replacement of search filter by a component that is capable of providing various search filters and a reset button
> Make search feature efficient in all the tables

- src/components/tables/EntriesTable/index.tsx
Related to https://github.com/idmc-labs/Helix2.0/issues/95
> Hide sources and publishers in 'My latest entries'

- README.md
- src/components/NumberBlock/index.tsx
- src/components/NumberBlock/styles.css
- src/components/TextBlock/index.tsx
- src/components/TextBlock/styles.css
- src/components/forms/CrisisForm/index.tsx
- src/components/forms/EventForm/index.tsx
- src/components/tables/EventsTable/index.tsx
- src/views/Country/index.tsx
- src/views/Country/styles.css
- src/views/Crises/index.tsx
- src/views/Crisis/index.tsx
- src/views/Crisis/styles.css
- src/views/Entry/EntryForm/queries.tsx
- src/views/Event/index.tsx
- src/views/Event/styles.css
- src/views/Report/index.tsx
- src/views/Report/styles.css
Addresses: https://github.com/idmc-labs/Helix2.0/issues/148#issue-925460022
https://github.com/idmc-labs/helix-server/pull/195#issue-687284912
- Event Detail section is added for each event of the event-list table that shows quick info about few details of the event. However, more details about the event may be required.
> Add Event detail section for each event data

- src/components/Downloads/DownloadedItem/index.tsx
- src/components/Downloads/index.tsx
- src/views/Countries/index.tsx
- src/views/Report/ReportCountryTable/index.tsx
- src/views/Report/ReportCrisisTable/index.tsx
- src/views/Report/ReportEntryTable/index.tsx
- src/views/Report/ReportEventTable/index.tsx
- src/views/Report/ReportFigureTable/index.tsx
Addresses :- 
https://github.com/idmc-labs/Helix2.0/issues/43
https://github.com/idmc-labs/Helix2.0/issues/154
Depends on :-
https://github.com/idmc-labs/helix-server/pull/195#issue-687284912
- Add export to multiple tables of each report
> Add Export feature to the multiple tables inside report

- src/components/GeoInput/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/205
> Update default Geolocation enum

- src/components/forms/EventForm/index.tsx
Addresses https://github.com/idmc-labs/Helix2.0/issues/215#issue-960368619
Depends on https://github.com/idmc-labs/helix-server/pull/209
> Fix the required fields of event form

- .github/workflows/ci.yml
Addresses New server endpoints.
* Detailed list or prose of changes
* Breaking changes
* Changes to configurations
> Update server endpoints

- src/components/Navbar/Downloads/DownloadedItem/index.tsx
- src/components/Navbar/Downloads/DownloadedItem/styles.css
- src/components/Navbar/Downloads/index.tsx
- src/components/tables/ContactsTable/index.tsx
- src/components/tables/EventsTable/index.tsx
- src/views/Actors/ActorTable/index.tsx
- src/views/Admin/UserRoles/UserActions/index.tsx
- src/views/Countries/index.tsx
- src/views/Crises/index.tsx
- src/views/Organizations/OrganizationTable/index.tsx
- src/views/Report/ReportCountryTable/index.tsx
- src/views/Report/ReportCrisisTable/index.tsx
- src/views/Report/ReportEventTable/index.tsx
- src/views/Reports/index.tsx
- https://github.com/idmc-labs/Helix2.0/issues/225
- Remove the permission check in reports table for exporting, however keeping the permission check consistent for adding new reports
> Allow all MEs to download report

- src/components/tables/EntriesTable/NudeFigureTable/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/queries.tsx
- src/views/Entry/EntryForm/schema.ts
-https://github.com/idmc-labs/Helix2.0/issues/212
- https://github.com/idmc-labs/helix-server/pull/212#issue-710384774
- Add new fields that record "Dis-aggregated Data" in the Entry section
- New fields include: LGBTIQ, indigenous People and Disability
> Add disaggregated input fields in Figure&Analysis

- src/components/Navbar/Downloads/DownloadedItem/index.tsx
- src/views/Events/EventsFilter/index.tsx
- src/views/Extraction/ExtractionFilters/index.tsx
- src/views/Report/index.tsx
- src/views/Reports/ReportForm/index.tsx
- https://github.com/idmc-labs/Helix2.0/issues/204
- https://github.com/idmc-labs/helix-server/pull/213
- Add new fields along with filtering feature for the respective fields: (Events, Entry-Tags, disaster Category, disaster-subcategory, Disaster-type, Disaster-sub type)
> Add more option in the add-new-report form

- src/views/Extraction/ExtractionEntriesTable/NudeFigureTable/index.tsx
- Fix the issues regarding specific columns not being sort-able in Extraction table
> Fix the sortable column issue in Extraction table

- src/components/HCaptcha/index.tsx
- src/components/HCaptcha/styles.css
> Fix captcha styling

- src/views/Entry/EntryForm/index.tsx
- src/views/Entry/EntryForm/styles.css
- src/views/Event/EventCloneForm/index.tsx
- src/views/Event/EventCloneForm/styles.css
- src/views/Event/index.tsx
- src/views/Event/styles.css
- https://github.com/idmc-labs/Helix2.0/issues/220
- https://github.com/idmc-labs/Helix2.0/issues/181
- https://github.com/idmc-labs/helix-server/pull/218
- Add a "Clone' button to a particular event detail in order to clone it into the Events Table
> Add EventClone feature to the Events Page

- .github/workflows/ci.yml
> Fix mmp link

- src/Root/App/Multiplexer/index.tsx
- src/components/forms/EventForm/index.tsx
- src/components/tables/EventsTable/index.tsx
- src/views/ContextualUpdates/ContextualUpdateFilter/index.tsx
- src/views/ContextualUpdates/index.tsx
- src/views/Crises/index.tsx
- src/views/Entry/EntryForm/FigureInput/styles.css
- src/views/Events/EventsFilter/index.tsx
- src/views/Extraction/ExtractionFilters/index.tsx
- src/views/Reports/ReportFilter/index.tsx
- src/views/Reports/index.tsx
- https://github.com/idmc-labs/Helix2.0/issues/61
- https://github.com/idmc-labs/helix-server/pull/221
- Add additional changes to the Contextual updates filter
> Additional Changes on table filters

- src/Root/App/styles.css
- src/components/forms/EventForm/index.tsx
- src/components/selections/EventMultiSelectInput/index.tsx
- src/components/tables/EntriesTable/NudeFigureTable/index.tsx
- src/components/tables/EventsTable/index.tsx
- src/views/Entry/EntryForm/AgeInput/index.tsx
- src/views/Entry/EntryForm/EntryCloneForm/index.tsx
- src/views/Entry/EntryForm/EntryCloneForm/styles.css
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/GeoLocationInput/index.tsx
- src/views/Entry/EntryForm/index.tsx
- src/views/Entry/EntryForm/styles.css
- src/views/Extraction/ExtractionEntriesTable/NudeFigureTable/index.tsx
- src/views/Report/ReportFigureTable/index.tsx
- src/views/Reports/ReportForm/index.tsx
- https://github.com/idmc-labs/Helix2.0/issues/218
- Add Chip-select feature in clone entry pop-up
> Add ChipSelect for entryClone

- src/components/forms/EventForm/index.tsx
- src/components/lists/MyResources/ResourceForm/index.tsx
- src/components/lists/MyResources/index.tsx
- src/components/selections/EventMultiSelectInput/index.tsx
- src/components/tables/ContactsTable/CommunicationTable/index.tsx
- src/components/tables/ContactsTable/index.tsx
- src/views/Actors/ActorTable/index.tsx
- src/views/Country/ContextualAnalysis/index.tsx
- src/views/Country/CountrySummary/index.tsx
- src/views/Entry/EntryForm/EntryCloneForm/index.tsx
- src/views/Entry/EntryForm/EntryCloneForm/styles.css
- src/views/Entry/EntryForm/index.tsx
- src/views/Event/index.tsx
- src/views/FigureTags/FigureTagsTable/index.tsx
- src/views/Organizations/OrganizationTable/index.tsx
- src/views/Report/ReportComments/index.tsx
- https://github.com/idmc-labs/Helix2.0/issues/
- Enable a feature of adding new events when cloning from ENTRY section
> Add new events while cloning in Entry

- src/components/SearchMultiSelectInputWithChip/index.tsx
- src/components/selections/OrganizationMultiSelectInput/index.tsx
- src/views/Entry/EntryForm/DetailsInput/index.tsx
- src/views/Organizations/OrganizationTable/OrganizationForm/index.tsx
- src/views/Organizations/OrganizationTable/index.tsx
- Feature to edit options of chip-select component specifically of OrganizationMultiSelect
> Add editable feature for chip select components

- src/views/Crises/index.tsx
- src/views/Extraction/ExtractionEntriesTable/NudeEntryTable/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/234
> Add sorting by event_count on Crisis and aggregates on Entry

- src/components/forms/ContactForm/index.tsx
- src/views/Entry/EntryComments/ReviewCommentForm/index.tsx
- src/views/Entry/EntryForm/AgeInput/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/GeoLocationInput/index.tsx
- src/views/Entry/EntryForm/index.tsx
- src/views/Entry/EntryForm/queries.tsx
- src/views/Entry/EntryForm/schema.ts
- src/views/Entry/EntryForm/types.ts
- src/views/Entry/EntryForm/utils.ts
- src/views/Extraction/ExtractionFilters/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/228
Depends on https://github.com/idmc-labs/helix-migration/pull/44
> Update use of disaggregatedAgeJson

- src/components/tables/EventsTable/EventsIgnore/index.tsx
- src/components/tables/EventsTable/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Extraction/ExtractionEntriesTable/NudeEntryTable/index.tsx
- src/views/Report/index.tsx
- https://freedcamp.com/view/2779007/tasks/panel/task/41914994
- https://freedcamp.com/view/2779007/tasks/panel/task/41914998
- Add ignore button column for "Recommended-Figures" table and un-ignore button for "Ignored-Events" table
> Add Event Ignore feature in QA dashboard

- src/views/Entry/EntryForm/AgeInput/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/index.tsx
- https://github.com/idmc-labs/meta-project/issues/1#issue-1178234522
- Clone latest figure from collection of figures in extraction
- While cloning, skip the cloning of figures and roles
> Feature to clone latest figure

- src/components/forms/CrisisForm/index.tsx
- src/components/forms/EventForm/index.tsx
- src/utils/common.ts
- src/views/Entry/EntryForm/DetailsInput/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/index.tsx
- src/views/Entry/EntryForm/queries.tsx
- https://github.com/idmc-labs/Helix2.0/issues/287
- https://github.com/idmc-labs/Helix2.0/issues/285
- https://github.com/idmc-labs/Helix2.0/issues/286
- https://github.com/idmc-labs/Helix2.0/issues/59
- https://github.com/idmc-labs/Helix2.0/issues/150
- https://github.com/idmc-labs/Helix2.0/issues/128
- https://freedcamp.com/view/2779007/tasks/panel/task/41913137
- Add a different way to showcase hints
- Add auto generate field data for event and crisis forms
- Add auto-generate feature for excerpt-idu field in EXTRACTION
> Auto-generate feature for excerpt-idu in Extraction

- src/components/forms/EventForm/index.tsx
- src/views/Entry/EntryForm/index.tsx
- src/views/Entry/EntryForm/schema.ts
- src/views/Events/EventsFilter/index.tsx
- Fixes the issue relative to context of violence not being submitted in figure-input modal
> Fix issue of violence context not being submitted

- src/views/Entry/EntryForm/index.tsx
- src/views/Extraction/ExtractionEntriesTable/NudeEntryTable/index.tsx
> Remove entry clone to other events

- src/components/forms/EventForm/index.tsx
- src/components/selections/EventListSelectInput/index.tsx
- src/components/tables/EntriesTable/NudeFigureTable/index.tsx
- src/components/tables/EventsTable/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/index.tsx
- src/views/Entry/EntryForm/queries.tsx
- src/views/Entry/EntryForm/schema.ts
- src/views/Entry/EntryForm/types.ts
- src/views/Event/index.tsx
- src/views/Extraction/ExtractionEntriesTable/NudeEntryTable/index.tsx
- src/views/Extraction/ExtractionEntriesTable/NudeFigureTable/index.tsx
- src/views/Report/ReportEventTable/index.tsx
- src/views/Report/ReportFigureTable/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/261
> Add event typology and figure typology on tables

- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/index.tsx
- src/views/Entry/EntryForm/queries.tsx
- src/views/Entry/EntryForm/schema.ts
- src/views/Entry/EntryForm/styles.css
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/43
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/45#event-6704509868
- https://github.com/idmc-labs/helix-server/pull/262
- Trends and patterns of displacement" field is hidden 
- Merge Analysis and calculation with caveats field
> Remove caveats and hide trends and pattern field

- src/components/forms/CrisisForm/index.tsx
- src/components/forms/CrisisForm/styles.css
- src/components/forms/EventForm/index.tsx
- src/components/forms/EventForm/styles.css
- src/views/Crises/CrisesFilter/index.tsx
- src/views/Crises/CrisesFilter/styles.css
- src/views/Events/EventsFilter/index.tsx
- src/views/Extraction/ExtractionFilters/index.tsx
- Add event statistics in event-form and crisis-form
- Edit search placeholder in crisis and event table
> Add event statistics and search placeholder

- src/views/Crises/CrisesFilter/index.tsx
- src/views/Events/EventsFilter/index.tsx
- src/views/Extraction/ExtractionFilters/index.tsx
- src/views/Reports/ReportFilter/index.tsx
- src/views/Reports/ReportForm/index.tsx
> Fix DateRangeInput props for ReportForm

- package.json
- src/components/CollapsibleContent/index.tsx
- src/components/CollapsibleContent/styles.css
- src/components/SmartLink.tsx
- src/components/tableHelpers/Link/index.tsx
- src/components/tableHelpers/StatusLink/index.tsx
- src/components/tableHelpers/index.tsx
- src/components/tables/EntriesTable/NudeFigureTable/index.tsx
- src/components/tables/EntriesTable/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/FigureInput/styles.css
- src/views/Entry/EntryForm/index.tsx
- src/views/Entry/index.tsx
- src/views/Extraction/ExtractionEntriesTable/NudeFigureTable/index.tsx
- src/views/Extraction/ExtractionEntriesTable/index.tsx
- src/views/Report/ReportFigureTable/index.tsx
- src/views/Report/index.tsx
- yarn.lock
- Implement hash redirection feature for extraction entry data where user will be redirected to the respective figure when a figure is title is clicked in the figure tab
> Implement hash feature for extraction

- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/FigureInput/styles.css
- Add a feature to generate figure name for each figure in extraction entry 
- Also apply enum fixes to sentence extraction in IDU description
> Add generated figure-name in extraction entry

- src/components/lists/MyResources/ResourceForm/index.tsx
- src/components/tableHelpers/Action.tsx
- src/components/tableHelpers/index.tsx
- src/components/tables/EntriesTable/NudeEntryTable/index.tsx
- src/components/tables/EntriesTable/NudeFigureTable/index.tsx
- src/components/tables/EventsTable/EventsAction/index.tsx
- src/components/tables/EventsTable/index.tsx
- src/views/Country/ContextualAnalysis/ContextualHistoryList/index.tsx
- src/views/Country/ContextualAnalysis/ContextualHistoryList/styles.css
- src/views/Country/CountrySummary/SummaryHistoryList/index.tsx
- src/views/Country/CountrySummary/SummaryHistoryList/styles.css
- src/views/Crises/index.tsx
- src/views/Entry/index.tsx
- src/views/Extraction/ExtractionEntriesTable/NudeEntryTable/index.tsx
- src/views/Extraction/ExtractionEntriesTable/NudeFigureTable/index.tsx
- src/views/Reports/index.tsx
- Contextual Analyses history modal updated with conditional rendering of data
- Confirmation box for deleting crisis, event, entries and report has been updated
- Comment tab is hidden during the creation of new entry
- Replace label name from "Groups" to "Group" in My Resource component
> Fixes of msg-box, comment tab, contextual-modal

- src/views/Entry/EntryForm/AgeInput/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/index.tsx
- src/views/Entry/EntryForm/queries.tsx
- src/views/Entry/EntryForm/schema.ts
- src/views/Entry/EntryForm/types.ts
Depends on https://github.com/idmc-labs/helix-migration/pull/65
Depends on https://github.com/idmc-labs/helix-server/pull/290
> Replace age "category" to age "from" and age "to"

- src/components/UrlPreview/index.tsx
- Use native pdf viewer for pdf
- Add sanbox for html preview iframe
> Use office preview and set google preview as fallback

- package.json
- src/components/forms/CommunicationForm/index.tsx
- src/components/forms/ContactForm/index.tsx
- src/components/forms/ParkedItemForm/index.tsx
- src/components/tables/ContactsTable/index.tsx
- src/views/Country/ContextualAnalysis/ContextualAnalysisForm/index.tsx
- src/views/Entry/EntryForm/DetailsInput/index.tsx
- src/views/MonitoringRegions/RegionalCoordinatorForm/index.tsx
- yarn.lock
- Issue: Commnuication form not visible: https://github.com/idmc-labs/helix2.0-meta/issues/103#issue-1285630301
- Issue: Fix auto-focus issues: https://github.com/idmc-labs/helix2.0-meta/issues/101#issue-1285319384
- issue: https://github.com/idmc-labs/helix2.0-meta/issues/102#issue-1285459643
- server: https://github.com/idmc-labs/helix-server/pull/291#issue-1276389746
- Fix issue of contacts table loading all data in the accordion
- Enable changes in the loading boolean for parking item form
> Fix issues of contact table and parked item form

- src/components/AuthSync/index.tsx
- src/components/Navbar/index.tsx
- src/components/forms/EventForm/index.tsx
- src/components/lists/MyResources/index.tsx
- src/components/tables/ContactsTable/CommunicationTable/index.tsx
- src/components/tables/ContactsTable/index.tsx
- src/components/tables/EventsTable/index.tsx
- src/components/tables/ParkedItemTable/index.tsx
- src/views/Actors/ActorTable/index.tsx
- src/views/Country/ContextualAnalysis/index.tsx
- src/views/Country/CountrySummary/index.tsx
- src/views/Crises/index.tsx
- src/views/Crisis/index.tsx
- src/views/Dashboard/index.tsx
- src/views/Entry/EntryComments/index.tsx
- src/views/Entry/EntryForm/DetailsInput/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Event/index.tsx
- src/views/FigureTags/FigureTagsTable/index.tsx
- src/views/MonitoringRegions/index.tsx
- src/views/Organizations/OrganizationTable/index.tsx
- src/views/Report/ReportComments/index.tsx
- src/views/Report/index.tsx
- src/views/Reports/index.tsx
- src/views/ViolenceContext/ViolenceContextTable/index.tsx
- Add a feature to set sizes in modal used in overall helix project
- Also make action buttons visible in parking lot table of DASHBOARD
> Add a feature to fix sizes of modal component

- src/components/tables/EventsTable/index.tsx
- Change the query variables for QA dashboard exports
> Change export variables for QA dashboard

- package.json
- src/components/forms/EventForm/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Events/EventsFilter/index.tsx
- src/views/Extraction/ExtractionFilters/index.tsx
- src/views/Reports/ReportForm/index.tsx
- yarn.lock
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/66#issue-1262976396
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/68#issue-1262995454
- Add changes to labels of entry fields 
- Update options list of displacement field by adding "FLOW" and "STOCK" as a primary category
> Add fixes to entry fields and options ordering

- src/utils/common.ts
- src/views/Entry/EntryForm/FigureInput/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/81#issuecomment-1169854425
- Fix the auto-generated figure title
> Fix generated texts as per the formats mentioned

- package.json
- src/Root/App/styles.css
- src/components/forms/EventForm/index.tsx
- src/components/selections/EventListSelectInput/index.tsx
- src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/EventsAction/index.tsx
- src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/index.tsx
- src/components/tables/EventsTable/index.tsx
- src/components/tables/ParkedItemTable/Action/index.tsx
- src/components/tables/ParkedItemTable/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/index.tsx
- src/views/Event/index.tsx
- src/views/MonitoringRegions/MonitoringExpertForm/index.tsx
- src/views/Report/styles.css
- Fix overflow on Report page
- Disable readonly text inputs
> Add clone event button

- package.json
- src/components/lists/MyResources/ResourceForm/index.tsx
- src/components/lists/MyResources/ResourcesAccordion/index.tsx
- src/components/lists/MyResources/index.tsx
- src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/index.tsx
- src/components/tables/EventsTable/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/index.tsx
- yarn.lock
Depends on https://github.com/idmc-labs/helix-server/pull/300
> Fix figure clone behavior

- src/components/forms/CrisisForm/index.tsx
- src/components/forms/EventForm/index.tsx
- src/utils/common.ts
- src/views/Entry/EntryForm/DetailsInput/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/122#issue-1294190268
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/127#issue-1295372858
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/121#issue-1294188773
- Fix date formats in the specified sectors such as event form, crisis form and entry form as mentioned
- Replace the generated field "cause" by "main trigger" in IDU text generation
> Fix generated texts and date formats

- src/views/MonitoringRegions/MonitoringExpertForm/index.tsx
- src/views/MonitoringRegions/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/305
> Use non-paginated response for monitoring country

- src/Root/App/Multiplexer/index.tsx
- src/components/Navbar/Downloads/index.tsx
- src/components/tables/ContactsTable/CommunicationTable/index.tsx
- src/components/tables/ContactsTable/index.tsx
- src/components/tables/EventsEntriesFiguresTable/index.tsx
- src/components/tables/EventsTable/index.tsx
- src/components/tables/ParkedItemTable/index.tsx
- src/views/Actors/ActorTable/index.tsx
- src/views/Admin/UserRoles/index.tsx
- src/views/ContextualUpdates/index.tsx
- src/views/Countries/index.tsx
- src/views/Country/ContextualAnalysis/ContextualHistoryList/index.tsx
- src/views/Country/CountrySummary/SummaryHistoryList/index.tsx
- src/views/Crises/index.tsx
- src/views/Dashboard/EntriesForReview/index.tsx
- src/views/Entry/EntryComments/index.tsx
- src/views/Extraction/ExtractionEntriesTable/index.tsx
- src/views/FigureTags/FigureTagsTable/index.tsx
- src/views/Organizations/OrganizationTable/index.tsx
- src/views/Report/ReportComments/index.tsx
- src/views/Report/ReportCountryTable/index.tsx
- src/views/Report/ReportCrisisTable/index.tsx
- src/views/Report/ReportEntryTable/index.tsx
- src/views/Report/ReportEventTable/index.tsx
- src/views/Report/ReportFigureTable/index.tsx
- src/views/Reports/index.tsx
- src/views/ViolenceContext/ViolenceContextTable/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/134#issue-1300591183
- Add debounced page element for every table in helix in order to prevent large number of unnecessary requests
- Also update the copyright year to latest
> Add debounced logic for request variables

- src/utils/selectionConstants.ts
Depends on https://github.com/idmc-labs/helix-server/pull/316
> Add RETURN and FAILED_RELOCATION_ELSEWHERE on flow

- src/views/Reports/ReportForm/index.tsx
- Issue:  https://github.com/idmc-labs/helix2.0-meta/issues/168
- server branch: https://github.com/idmc-labs/helix-server/pull/318#issue-1325351314
- Add roles field in the report form
> Finalize roles field in report form

- src/components/forms/ContactForm/index.tsx
- src/components/selections/OrganizationMultiSelectInput/index.tsx
- src/components/selections/OrganizationSelectInput/index.tsx
- src/views/Entry/EntryForm/queries.tsx
- src/views/Extraction/ExtractionFilters/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/124
- Added country name in the options of publishers and sources to make it more descriptive
> Add country name in the sources optionlist

- src/views/Entry/EntryForm/FigureInput/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/136
- Move geo-spatial section above the quantifier section as per requested
> Re-alignment of geo-spatial section

- src/utils/common.ts
- src/views/Entry/EntryForm/FigureInput/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/81
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/148
- Update figure title generation scheme
> Add latest updates to figure title

- src/utils/selectionConstants.ts
- src/views/Entry/EntryForm/queries.tsx
- Depends on https://github.com/idmc-labs/helix-server/pull/322
- Addresses https://github.com/idmc-labs/helix2.0-meta/issues/178
* Detailed list or prose of changes
* Breaking changes
* Changes to configurations
> Fetch displacementOccurred on entry's figure

- src/components/GeoInput/index.tsx
Related to https://github.com/idmc-labs/helix2.0-meta/issues/156
> Check supportedCountries on OSMName

- src/components/forms/CrisisForm/index.tsx
- src/components/forms/EventForm/index.tsx
- src/views/Entry/EntryForm/DetailsInput/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/194#issue-1358351085
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/197#issue-1383803528
- Change conditional logic for auto generated fields in components such as Figure, Event and Crisis
> Fix auto-generated names and zero stocks issue

- package.json
- src/Root/App/Multiplexer/index.tsx
- src/components/Navbar/Downloads/DownloadedItem/index.tsx
- src/utils/common.ts
- src/utils/selectionConstants.ts
- src/views/Countries/CountriesFilter/index.tsx
- src/views/Country/index.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Extraction/ExtractionFilters/index.tsx
- src/views/Reports/ReportForm/index.tsx
- yarn.lock
Addresses https://github.com/idmc-labs/helix2.0-meta/issues/196
Addresses https://github.com/idmc-labs/helix2.0-meta/issues/193
> Fix method to get date from 'yyyy-mm-dd' string

- src/components/selections/OrganizationMultiSelectInput/index.tsx
- src/components/selections/OrganizationSelectInput/index.tsx
> Skip ordering field on query when using orderByCountry

- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/index.tsx
- Task: https://github.com/idmc-labs/helix2.0-meta/issues/198
- Change the functionality of "Add Figure" button
- Add "Clone Figure" button to each figure
> Add the clone feature back to each figure

- src/Root/App/Multiplexer/index.tsx
- src/components/Navbar/Downloads/index.tsx
- src/components/Navbar/index.tsx
- src/components/Navbar/styles.css
- src/components/selections/OrganizationMultiSelectInput/index.tsx
- src/components/selections/OrganizationSelectInput/index.tsx
- src/config/routes.tsx
- src/views/Entry/EntryForm/FigureInput/index.tsx
- src/views/Entry/EntryForm/index.tsx
- src/views/Entry/styles.css
- src/views/Extraction/SavedFiltersList/index.tsx
- src/views/Notifiations/NotificationCategory/index.tsx
- src/views/Notifiations/NotificationCategory/styles.css
- src/views/Notifiations/index.tsx
- src/views/Notifiations/styles.css
- Add notifications section to make a list of all events that occurred throughout the application
> Add notifications section for all events

- src/components/ProgressBar/index.tsx
- src/components/forms/EventForm/index.tsx
- src/components/tableHelpers/StackedProgress/index.tsx
- src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/index.tsx
- src/views/Report/ReportEventTable/index.tsx
- Include "include triangulation in QA" in Event modal
- Show progress for event
> Show progress for event

- src/components/PageHeader/index.tsx
- src/components/PageHeader/styles.css
- src/components/TrafficLightInput/ReviewComments/CommentForm/index.tsx
- src/components/forms/EntryForm/DetailsInput/styles.css
- src/components/lists/MyResources/ResourceItem/index.tsx
- src/views/Event/index.tsx
- src/views/QADashboard/index.tsx
- src/views/Report/ReportComments/CommentForm/index.tsx
* changes in the event page
- Add review link button
- Show review progress status
* Remove unused styling class name
> Add review button link in event page

- src/config/routes.tsx
> Fix - event review permission

- src/views/Notifications/index.tsx
- Issue: https://github.com/idmc-labs/helix-client/issues/392
- Server branch: https://github.com/idmc-labs/helix-server/pull/374#issue-1453018264 
- Added a query to show count for notification category
> Add notification count for notification categories

- src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/EventsAction/index.tsx
- src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/index.tsx
> Fix event review page visibility

- src/components/CollapsibleContent/index.tsx
- src/components/Navbar/index.tsx
- src/components/TrafficLightInput/styles.css
- src/components/forms/EntryForm/FigureInput/index.tsx
- src/components/forms/EntryForm/FigureInput/styles.css
- src/components/forms/EntryForm/queries.tsx
- src/components/selections/EventListSelectInput/index.tsx
- src/components/selections/EventListSelectInput/styles.css
- src/views/Admin/UserRoles/index.tsx
- src/views/EventReview/index.tsx
- src/views/Notifications/NotificationContent/index.tsx
- Show if a user is ME or RC on navbar besides the username
- Show warning on figures whose events are signed off or approved
- Fix figure link on notification content
> Show warning on figures whose events are signed off or approved

- src/components/TrafficLightInput/ReviewComments/CommentForm/index.tsx
> Change descrption on Review comment form

- src/components/TrafficLightInput/ReviewComments/index.tsx
- src/components/TrafficLightInput/index.tsx
- src/components/forms/EntryForm/FigureInput/index.tsx
- src/components/forms/EntryForm/GeoLocationInput/index.tsx
- src/components/forms/EntryForm/index.tsx
- src/components/forms/EntryForm/queries.tsx
- src/views/EventReview/index.tsx
- src/views/Notifications/NotificationContent/index.tsx
- src/views/Notifications/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/413
> Disable review on figures that do not need to be reviewed

- src/components/GeoInput/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/408
Related to https://github.com/idmc-labs/helix2.0-meta/issues/209
> Remove PF from supported countries in osmnames

- src/components/forms/EntryForm/FigureInput/index.tsx
- src/views/Report/Analysis/AnalysisUpdateForm/index.tsx
- src/views/Report/Challenges/ChallengesUpdateForm/index.tsx
- src/views/Report/Methodology/MethodologyUpdateForm/index.tsx
- src/views/Report/Significant/SignificantUpdatesForm/index.tsx
- src/views/Report/Summary/SummaryUpdateForm/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/250#issue-1496163425
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/253#issue-1497762489
-  Make submit button visible for figure analysis and multiple other input fields
- Fix the issue of warning message popping up when adding a new figure
> Fix issues relative to figure 

- src/components/forms/EntryForm/FigureInput/index.tsx
- src/components/forms/EntryForm/index.tsx
> Fix entry form value set on create and update

- src/components/TrafficLightInput/ReviewComments/CommentForm/index.tsx
- src/components/forms/EntryForm/FigureInput/index.tsx
- src/components/forms/EntryForm/index.tsx
- src/components/forms/EventForm/index.tsx
- src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/EventsAction/index.tsx
- src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/QaSettingsModal/index.tsx
- src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/TriangulationModal/index.tsx
- src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/index.tsx
- src/components/tables/EventsTable/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/416
Related to
- https://github.com/idmc-labs/helix2.0-meta/issues/172
- https://github.com/idmc-labs/helix2.0-meta/issues/247
- https://github.com/idmc-labs/helix2.0-meta/issues/232
* Fix comment type colors 
* Add triangulation Modal
* Add comment in the figure unit field.
> Fix - Event review

- src/components/forms/EntryForm/FigureInput/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/301#issuecomment-1403048381
- Fix the logic to show idu generation button in for the entry page
> Fix the conditional logic for idu generation

- src/views/Report/PublicFigureAnalysis/PublicFigureUpdateForm/index.tsx
- src/views/Report/PublicFigureAnalysis/PublicFigureUpdateForm/styles.css
- src/views/Report/PublicFigureAnalysis/query.tsx
- src/views/Report/index.tsx
- https://github.com/idmc-labs/helix2.0-meta/issues/302#issue-1555288204
- https://github.com/idmc-labs/helix-server/pull/432
- Add a new section in report details for public figure analysis in report details
> Public figure analysis section in report detail

- src/components/forms/EntryForm/schema.ts
- https://github.com/idmc-labs/helix2.0-meta/issues/308
> Make 'url' a conditinal field

- src/components/selections/EventListSelectInput/index.tsx
- src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/index.tsx
- src/components/tables/ReportsTable/index.tsx
- src/views/Countries/index.tsx
- src/views/Country/index.tsx
- src/views/Crises/index.tsx
- src/views/Crisis/index.tsx
- src/views/Event/index.tsx
- src/views/Report/ReportCountryTable/index.tsx
- src/views/Report/ReportCrisisTable/index.tsx
- src/views/Report/ReportEventTable/index.tsx
- src/views/Report/index.tsx
> Rename new displacements to internal displacements

- package.json
- src/components/selections/UserMultiSelectInput/index.tsx
- src/components/selections/UserSelectInput/index.tsx
- yarn.lock
Related to https://github.com/idmc-labs/helix2.0-meta/issues/323
Depends on https://github.com/idmc-labs/helix-server/pull/499
- Fix issues with copying of values from select input
- Get inactive users on user select inputs
- Mark inactive users on use select inputs with `(Inactive)` suffix.
> Fix issue with copying value form select inputs

- src/config/routes.tsx
- src/utils/selectionConstants.ts
- src/views/Admin/UserRoles/UserFilter/index.tsx
- src/views/ApiUsage/ApiRecordsTable/index.tsx
- src/views/FigureTags/FigureTagsTable/index.tsx
- Only show REGIONAL_COORDINATOR and MONITORING_EXPERT option
> Show PEOPLE_DISPLACED_ACROSS_BORDERS_FLOW option

- src/components/GeoInput/index.tsx
- src/components/TrafficLightInput/ReviewComments/CommentForm/index.tsx
- src/components/forms/EntryForm/FigureInput/index.tsx
- src/utils/selectionConstants.ts
- Allow users to mark green review without comment
- Hide "people displaced across borders" option for figure category
- https://github.com/idmc-labs/helix2.0-meta/issues/296
- https://github.com/idmc-labs/helix2.0-meta/issues/942
- https://github.com/idmc-labs/helix2.0-meta/issues/924
> Add location type "origin and destination"

- src/components/ButtonLikeLink/index.tsx
- src/components/forms/EntryForm/FigureInput/index.tsx
Addresses https://github.com/idmc-labs/helix2.0-meta/issues/938
> Link event in entry edit page

- src/components/tables/EntriesFiguresTable/index.tsx
> Properly override filters on EntriesFiguresTable

- src/components/forms/EntryForm/FigureInput/index.tsx
- src/components/forms/EntryForm/index.tsx
- src/components/forms/EntryForm/queries.tsx
- src/components/forms/EntryForm/schema.ts
- src/components/forms/EntryForm/types.ts
- src/components/forms/EntryForm/utils.ts
- src/components/forms/EventForm/index.tsx
- src/components/rawTables/EventsTable/EventsFilter/index.tsx
- src/components/tableHelpers/Status/index.tsx
- src/hooks/useBulkSaveRegister.ts
- src/views/EventReview/index.tsx
- src/views/QADashboard/index.tsx
- https://github.com/idmc-labs/helix2.0-meta/issues/140
- https://github.com/idmc-labs/helix-server/pull/511
> Batch update of figures

- src/components/forms/EntryForm/index.tsx
- src/components/forms/EntryForm/utils.ts
- src/components/forms/EventForm/EventCodeInput/index.tsx
- src/components/forms/EventForm/EventCodeInput/styles.css
- src/components/forms/EventForm/index.tsx
- src/utils/common.ts
- src/views/Event/index.tsx
- https://github.com/idmc-labs/helix2.0-meta/issues/963
- https://github.com/idmc-labs/helix2.0-meta/issues/967
- https://github.com/idmc-labs/helix2.0-meta/issues/971
- https://github.com/idmc-labs/helix2.0-meta/issues/972
- https://github.com/idmc-labs/helix2.0-meta/issues/989
- https://github.com/idmc-labs/helix2.0-meta/issues/996
- https://github.com/idmc-labs/helix-server/pull/543
* Remove old event code section.
* Add new inputs section for event code.
* Add new file for `EventCodeInput` component.
* Add validations for event code country.
> Add new event code 

- src/components/ChartAxes/styles.css
- src/components/IdpChart/index.tsx
- src/components/IdpChart/styles.css
- src/components/InfoPopup/styles.module.css
- src/components/Navbar/styles.css
- src/components/NdChart/index.tsx
- src/components/ReducedListDisplay/styles.module.css
- src/hooks/useChartData.ts
- src/utils/common.ts
- src/views/Admin/UserRoles/UserFilter/index.tsx
- Fix ND chart for single data points
- Remove and replace incorrect css tokens
- Make navbar menu scrollable in smaller screen (with hidden scrollbar)
> Fix New Displacement Chart

- src/components/selections/OrganizationMultiSelectInput/index.tsx
> Fix filtering for organization on search multiselect input

- src/components/DateTime/index.tsx
- src/components/IdpChart/index.tsx
- src/components/NdChart/index.tsx
- src/hooks/useCombinedChartData.ts
- src/utils/common.ts
> Fix issue with the date locale format

- src/components/DateTime/index.tsx
- src/components/IdpChart/index.tsx
- src/components/NdChart/index.tsx
- src/components/rawTables/useFigureTable/FiguresFilterOutput/index.tsx
- src/hooks/useCombinedChartData.ts
- src/utils/common.ts
- Use data formatting on filter item in Report, Crisis, Event, Country
- Use data formatting on IDPs chart "as of" information
> Add utility for formatting date and datetime

- src/components/DateTime/index.tsx
- src/components/rawTables/useEventTable/index.tsx
- src/components/tables/CrisesTable/index.tsx
- src/components/tables/EventsTable/index.tsx
- src/utils/common.ts
- src/views/Crises/index.tsx
- src/views/Crises/styles.css
- src/views/Events/index.tsx
- src/views/Events/styles.css
- https://github.com/idmc-labs/helix2.0-meta/issues/948 
* Add figures filter in event page.
* Add figures filter in crises page.
> Add figure filter in event table page

- src/components/tables/ParkedItemTable/index.tsx
- src/views/Admin/UserRoles/index.tsx
- src/views/FigureTags/FigureTagsTable/index.tsx
- src/views/MonitoringRegions/index.tsx
- src/views/ViolenceContext/ViolenceContextTable/index.tsx
- https://github.com/idmc-labs/helix-server/pull/578
- https://github.com/idmc-labs/helix2.0-meta/issues/1084
- https://github.com/idmc-labs/helix2.0-meta/issues/1083
- https://github.com/idmc-labs/helix2.0-meta/issues/1087
- https://github.com/idmc-labs/helix2.0-meta/issues/1085
- https://github.com/idmc-labs/helix2.0-meta/issues/1082
* Add export on parking lot table
* Add export on figure tags table
* Add export on Admin table
* Add export on the Monitoring regions table
* Add export on Context of violence table
> Add export on table data

- src/views/MonitoringRegions/index.tsx
- https://github.com/idmc-labs/helix2.0-meta/issues/315
* Make monitoring region table action column consistent to parking lot table
> Fix monitoring region table action column consistent

- src/views/Admin/UserRoles/index.tsx
- src/views/MonitoringRegions/index.tsx
- src/views/ViolenceContext/ViolenceContextTable/index.tsx
- https://github.com/idmc-labs/helix-server/pull/578
* Change export mutation variable name as change in server side
- [ x temporary files, auto-generated files or secret keys
> Fix export variables name

- src/components/forms/EntryForm/index.tsx
- https://github.com/idmc-labs/helix-server/pull/570
> Remove disaggregationStrataJson

- src/components/forms/EntryForm/index.tsx
- https://github.com/idmc-labs/helix-server/pull/559
> Remove wasSubfact from Figure

- src/Root/App/Multiplexer/index.tsx
- src/components/forms/ClientRecordForm/index.tsx
- src/views/Admin/UserRoles/index.tsx
- src/views/SignIn/index.tsx
Depends on 
- https://github.com/idmc-labs/helix-server/pull/566/
- Fix user portfolio metadata types in query
> Fix portfolio roles type

- src/components/forms/ClientRecordForm/index.tsx
- src/views/ApiUsage/ClientRecordsTable/index.tsx
Addresses
Depends on 
- https://github.com/idmc-labs/helix-server/pull/573
* Add form fields for client code
* Add mutation and query
> Add form fields and mutation for client code generation

- src/views/ApiUsage/ClientRecordsTable/ClientRecordsFilters/index.tsx
Addresses 
- https://github.com/idmc-labs/helix2.0-meta/issues/1128
Depends on 
- https://github.com/idmc-labs/helix-server/pull/593
* Add use cases filter in clients table
> Add use cases filter in clients table

- src/components/forms/ClientRecordForm/index.tsx
- src/components/rawTables/useEntryTable/index.tsx
- src/types/index.ts
- src/views/ContextualUpdates/index.tsx
- src/views/Extraction/index.tsx
- src/views/Report/index.tsx
Addresses 
- https://github.com/idmc-labs/helix2.0-meta/issues/1147
*Fix Report PFA edit
> Fix report PFA edit

- src/views/Report/index.tsx
Addresses
- https://github.com/idmc-labs/helix2.0-meta/issues/1138
* Rename miscellaneous section title in report page
> Rename miscellaneous section in report

- src/views/Report/index.tsx
- https://github.com/idmc-labs/helix-server/pull/603
> May Release

- README.md
This PR significantly enhances our project's README, providing a more detailed and structured overview of Helix 2.0. The updated README aims to improve project understanding for new contributors and streamline the development process.
- **Expanded Table of Contents**: Provides a clear overview of the README structure.
- **Detailed Project Overview**: Offers a comprehensive introduction to Helix 2.0 and its main features.
- **Repository Structure**: Outlines the organization of project files and directories.
- **Architecture Overview**: Describes the high-level architecture and key dependencies.
- **Enhanced Setup Instructions**: Provides step-by-step guidance for environment setup and installation.
- **Deployment Process**: Includes instructions for production builds and AWS …
> Docs: Comprehensive README update
